name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run build

  packages-build:
    name: Packages Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run packages:build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run test:ci
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
        with:
          fail_ci_if_error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npx --no-install ts-standard

  docker-buildx:
    needs: [ build, lint ]
    name: Docker Buildx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25

      - name: Build platforms
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          push: false
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/defich/playground:latest

  docker-sanity:
    needs: [ build, lint ]
    name: Docker Sanity Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Setup docker containers
        run: docker-compose -f .github/workflows/ci/docker-compose.yml up -d

      - name: Wait for :3001/_actuator/probes/liveness
        run: .github/workflows/ci/wait-for http://localhost:3001/_actuator/probes/liveness -t 240

      - name: Wait for :3002/_actuator/probes/liveness
        run: .github/workflows/ci/wait-for http://localhost:3002/_actuator/probes/liveness -t 240

      - name: Wait for :8082/ping
        run: .github/workflows/ci/wait-for http://localhost:8082/ping -t 120

      - name: Sanity testing
        uses: matt-ball/newman-action@64419a64bd84915e081828373fb872be6def2712
        with:
          collection: .github/workflows/ci/postman_collection.json
