name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  jellyfish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16

      - run: npx npm-check-updates -l m -u --deep --target newest --pre -f "/^defichain|@defichain\/.+/" -x "/^@defichain\/(whale|playground)-.+/"

      - name: Upgrade dependencies
        run: |
          if ! git diff-index --quiet HEAD; then
            npm i
          else
            echo "no file has been changed"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: Bump @defichain/jellyfish dependencies
          commit-message: Bump @defichain/jellyfish dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/jellyfish` dependencies to the latest release.
          branch: defichain-bot/bump-jellyfish-deps
